apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: hudtemp-aggregated
  labels:
    manufacturer: 'tmr'
  fault_tolerance:
    description: 'Tolerates the failure of one of the physical hudtemp sensors'
    type_of_fault_tolerance: 'Triple modular redundancy'
spec:
  deviceModelRef:
    name: hudtemp-model
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: ''
            operator: In
            values:
              - <edge_node>
status:
  twins:
    - propertyName: temperature
      desired:
        metadata:
          type: string
        value: ''
    - propertyName: humidity
      desired:
        metadata:
          type: string
        value: ''