apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: kubeedge-sensor2-mapper
  name: kubeedge-sensor2-mapper
  namespace: default
spec:
  selector:
    matchLabels:
      k8s-app: kubeedge-sensor2-mapper
  template:
    metadata:
      labels:
        k8s-app: kubeedge-sensor2-mapper
    spec:
      nodeName: <edge_node>
      hostNetwork: true
      containers:
      - name: kubeedge-sensor2-mapper
        image: kubeedge-sensor-mapper2
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
