apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: kubeedge-bl-gw
  name: kubeedge-bluetooth-gateway
  namespace: default
spec:
  selector:
    matchLabels:
      k8s-app: kubeedge-bl-gw
  template:
    metadata:
      labels:
        k8s-app: kubeedge-bl-gw
    spec:
      nodeName: <edge_node>
      hostNetwork: true
      containers:
      - name: kubeedge-bl-gw
        image: kubeedge-bl-gw:v1.0
        imagePullPolicy: IfNotPresent
      restartPolicy: Always