apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: virt-hudtemp
  labels:
    manufacturer: 'xiaomi'
spec:
  deviceModelRef:
    name: hudtemp-model
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: ''
            operator: In
            values:
              - kubecloud
status:
  twins:
    - propertyName: temperature
      desired:
        metadata:
          type: string
        value: ''
    - propertyName: humidity
      desired:
        metadata:
          type: string
        value: ''